#!/bin/bash
# Script to populate home directory
# Written by Chad Sebesta

# Directories to create
DIRECTORIES="
	Desktop
	Documents
	Downloads
	Music
	Pictures
	Public
	Templates
	Videos
	"

# Create directories
for directory in $DIRECTORIES; do

	# Test if directory exists
	if [[ -d "$HOME/$directory" ]]; then

		echo "$directory exists"

	# Make directory and test for errors
	else

		mkdir "$HOME/$directory" > /dev/null 2>&1 \
		&& echo "$directory created" \
		|| echo "$directory creation failed"

	fi

done
