#!/bin/bash
# Script for updating firefox to the latest version

# Download latest version of firefox
echo -n "Downloading the latest version of firefox... "
wget -q -O /tmp/firefox.tar.bz2 https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US \
	&& echo "OK" \
	|| echo "Failed"

# Extract to /opt and overwrite
if [ -d "/opt/firefox" ]; then
	echo "Overwirte existing firefox installation?"
	exit
else
	print "Installing firefox..."
fi

tar xjf /tmp/firefox.tar.bz2 -C /opt
